production: &default
  facebook:
    app_id: <%= ENV["FACEBOOK_APP_ID"] %>
    secret: <%= ENV["FACEBOOK_SECRET"] %>
    site_name: Victory Kit
    image: http://act.watchdog.net/images/petition-fb.png

staging: *default

test: *default
    
development: *default

vagrant: *default
